AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Streams DynamoDB table changes to EventBridge (uksb-1tthgi812) (tag:dynamodb-eventbridge-java)
Resources:
  #DynamoDB Streams specification
  PulseAbnormalValuesTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: pulse_abnormal_values
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  PulseValuesStream:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: pulse_values
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: N
        - AttributeName: timestamp
          AttributeType: N
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
        - AttributeName: timestamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

  # Define the publisher Lambda function with permissions
  PulseAbnormalValues:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: pulse-jump-analyzer
      Handler: telran.pulse.monitoring.App::pulseAnalyzer
      Runtime: java17
      Architectures:
        - x86_64
      Timeout: 30
      MemorySize: 512
      Events:
        TableRecordChange:
          Type: DynamoDB
          Properties:
            StartingPosition: LATEST
            Stream: !GetAtt PulseValuesStream.StreamArn
      Policies:
        - Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - dynamodb:*
 